### ISSUE TITLE
 Execute task service error on influxdb

### ISSUE THREAD

**Issue by blackinno** [mesg-foundation/engine#1537] opened 2019-11-29 03:38 UTC
**Describe the bug** 
Listen to the transfer event on ERC-20 then save data to influxdb but all data from transfer events aren't saved to the database.

**To Reproduce**
Run this script :
```js
const Application = require('@mesg/application')

const mesg = new Application()

async function main() {
  const erc20 = await mesg.resolve('ethereum-erc20')
  const runnerHash = await mesg.resolveRunner('influxdb')

  mesg.listenEvent({ filter: { instanceHash: erc20, key: 'transfer' } }).on('data', async event => {
    const transfer = mesg.decodeData(event.data)
    console.log('transfer type: ', typeof transfer, ' transfer', transfer)
    try {
      const result = await mesg.executeTask({
        executorHash: runnerHash,
        eventHash: event.hash,
        taskKey: 'write',
        inputs: mesg.encodeData({
          measurement: 'transfer',
          tags: {
            block: transfer.blockNumber,
            address: transfer.contractAddress,
            from: transfer.from,
            to: transfer.to
          },
          fields: { value: parseFloat(transfer.value) }
        })
      })
      console.log('a result received:', result)
    } catch (error) {
       console.error('an error has occurred:', error)
    }
  })
  console.log('application is running and listening for transfer events')
}

main()
```
**Screenshots**

*log from influxdb service*:
<img width="840" alt="Screen Shot 2562-11-29 at 10 10 23" src="https://user-images.githubusercontent.com/16553272/69841599-7b37c880-1292-11ea-8067-81121211105d.png">

*log from script*:
<img width="1066" alt="Screen Shot 2562-11-29 at 10 26 00" src="https://user-images.githubusercontent.com/16553272/69841677-c2be5480-1292-11ea-84a4-d3236c132c89.png">

**Comment by NicolasMahe** [comment] 2019-12-05 05:21
has the problem been resolved with https://github.com/mesg-foundation/engine/issues/1539 ?

**Comment by antho1404** [comment] 2019-12-05 05:42
No, there is still an error because of the sequence. It should be fixed when https://github.com/mesg-foundation/engine/issues/1538 is fixed.

**Comment by antho1404** [comment] 2019-12-18 03:24
I tested this with https://github.com/mesg-foundation/engine/pull/1556 and the problem is solved.
This issue will be fixed when the PR is merged

**Closed** 2019-12-18 07:48 UTC
